apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: echo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: microdemo/echo
          ports:
            - containerPort: 80
